from enum import IntEnum
from typing import overload

class EMITTER_MANIP(IntEnum):
	# general manipulators
	Auto 		= ...
	TagByKind 	= ...
	Newline 	= ...

	# output character set
	EmitNonAscii 	= ...
	EscapeNonAscii 	= ...
	EscapeAsJson 	= ...

	# string manipulators
	# Auto, # duplicate
	SingleQuoted 	= ...
	DoubleQuoted 	= ...
	Literal 		= ...

	# null manipulators
	LowerNull = ...
	UpperNull = ...
	CamelNull = ...
	TildeNull = ...

	# bool manipulators
	YesNoBool 		= ... # yes, no
	TrueFalseBool 	= ... # true, false
	OnOffBool 		= ... # on, off
	UpperCase 		= ... # TRUE, N
	LowerCase 		= ... # f, yes
	CamelCase 		= ... # No, Off
	LongBool 		= ... # yes, On
	ShortBool 		= ... # y, t

	# int manipulators
	Dec = ...
	Hex = ...
	Oct = ...

	# document manipulators
	BeginDoc 	= ...
	EndDoc 		= ...

	# sequence manipulators
	BeginSeq 	= ...
	EndSeq 		= ...
	Flow 		= ...
	Block 		= ...

	# map manipulators
	BeginMap 	= ...
	EndMap 		= ...
	Key 		= ...
	Value 		= ...
	# Flow, # duplicate
	# Block, # duplicate
	# Auto, # duplicate
	LongKey 	= ...

Auto: EMITTER_MANIP 			= EMITTER_MANIP.Auto
TagByKind: EMITTER_MANIP 		= EMITTER_MANIP.TagByKind
Newline: EMITTER_MANIP 			= EMITTER_MANIP.Newline
EmitNonAscii: EMITTER_MANIP 	= EMITTER_MANIP.EmitNonAscii
EscapeNonAscii: EMITTER_MANIP 	= EMITTER_MANIP.EscapeNonAscii
EscapeAsJson: EMITTER_MANIP 	= EMITTER_MANIP.EscapeAsJson
SingleQuoted: EMITTER_MANIP 	= EMITTER_MANIP.SingleQuoted
DoubleQuoted: EMITTER_MANIP 	= EMITTER_MANIP.DoubleQuoted
Literal: EMITTER_MANIP 			= EMITTER_MANIP.Literal
LowerNull: EMITTER_MANIP 		= EMITTER_MANIP.LowerNull
UpperNull: EMITTER_MANIP 		= EMITTER_MANIP.UpperNull
CamelNull: EMITTER_MANIP 		= EMITTER_MANIP.CamelNull
TildeNull: EMITTER_MANIP 		= EMITTER_MANIP.TildeNull
YesNoBool: EMITTER_MANIP 		= EMITTER_MANIP.YesNoBool
TrueFalseBool: EMITTER_MANIP 	= EMITTER_MANIP.TrueFalseBool
OnOffBool: EMITTER_MANIP 		= EMITTER_MANIP.OnOffBool
UpperCase: EMITTER_MANIP 		= EMITTER_MANIP.UpperCase
LowerCase: EMITTER_MANIP 		= EMITTER_MANIP.LowerCase
CamelCase: EMITTER_MANIP 		= EMITTER_MANIP.CamelCase
LongBool: EMITTER_MANIP 		= EMITTER_MANIP.LongBool
ShortBool: EMITTER_MANIP 		= EMITTER_MANIP.ShortBool
Dec: EMITTER_MANIP 				= EMITTER_MANIP.Dec
Hex: EMITTER_MANIP 				= EMITTER_MANIP.Hex
Oct: EMITTER_MANIP 				= EMITTER_MANIP.Oct
BeginDoc: EMITTER_MANIP 		= EMITTER_MANIP.BeginDoc
EndDoc: EMITTER_MANIP 			= EMITTER_MANIP.EndDoc
BeginSeq: EMITTER_MANIP 		= EMITTER_MANIP.BeginSeq
EndSeq: EMITTER_MANIP 			= EMITTER_MANIP.EndSeq
Flow: EMITTER_MANIP 			= EMITTER_MANIP.Flow
Block: EMITTER_MANIP 			= EMITTER_MANIP.Block
BeginMap: EMITTER_MANIP 		= EMITTER_MANIP.BeginMap
EndMap: EMITTER_MANIP 			= EMITTER_MANIP.EndMap
Key: EMITTER_MANIP 				= EMITTER_MANIP.Key
Value: EMITTER_MANIP 			= EMITTER_MANIP.Value
LongKey: EMITTER_MANIP 			= EMITTER_MANIP.LongKey

class Node:

	def __init__(self) -> None: ...

	def as_bool(self) -> bool: ...
	def as_int(self) -> int: ...
	def as_float(self) -> float: ...
	def as_str(self) -> str: ...

	def WriteTo(self, inObject: object) -> None: ...

	def __rshift__(self, inObject: object) -> None: ...

	@overload
	def __getitem__(self, inKey: str) -> Node: ...

	@overload
	def __getitem__(self, inKey: int) -> Node: ...

class Emitter:

	def __init__(self) -> None: ...

	def c_str(self) -> str: ...
	def size(self) -> int: ...

	def good(self) -> bool: ...
	def GetLastError(self) -> str: ...

	def SetOutputCharset(self, 		inValue: EMITTER_MANIP) -> bool: ...
	def SetStringFormat(self, 		inValue: EMITTER_MANIP) -> bool: ...
	def SetBoolFormat(self, 		inValue: EMITTER_MANIP) -> bool: ...
	def SetNullFormat(self, 		inValue: EMITTER_MANIP) -> bool: ...
	def SetIntBase(self, 			inValue: EMITTER_MANIP) -> bool: ...
	def SetSeqFormat(self, 			inValue: EMITTER_MANIP) -> bool: ...
	def SetMapFormat(self, 			inValue: EMITTER_MANIP) -> bool: ...
	def SetIndent(self, 			inValue: int) -> bool: ...
	def SetPreCommentIndent(self, 	inValue: int) -> bool: ...
	def SetPostCommentIndent(self, 	inValue: int) -> bool: ...
	def SetFloatPrecision(self, 	inValue: int) -> bool: ...
	def SetDoublePrecision(self, 	inValue: int) -> bool: ...
	def SetShowTrailingZero(self, 	inbValue: bool) -> bool: ...
	def RestoreGlobalModifiedSettings(self) -> bool: ...

	def Start(self, inManip: EMITTER_MANIP) -> Emitter: ...
	def Type(self, inManip: EMITTER_MANIP) -> Emitter: ...
	def Value(self, inObject: object) -> Emitter: ...
	def End(self, inManip: EMITTER_MANIP) -> None: ...

	@overload
	def __lshift__(self, inManip: EMITTER_MANIP) -> Emitter: ...

	@overload
	def __lshift__(self, inObject: object) -> Emitter: ...

def Load(inSource: str) -> Node: ...
def LoadFile(inFileName: str) -> Node: ...