from . import sinks

from collections.abc import Iterable
from datetime import datetime
from typing import overload
from enum import IntEnum



class level(IntEnum):
	trace = ...
	debug = ...
	info = ...
	warn = ...
	err = ...
	critical = ...
	off = ...
	n_levels = ...

class color_mode(IntEnum):
	always = ...
	automatic = ...
	never = ...

class source_loc:

	@overload
	def __init__(self) -> None: ...

	@overload
	def __init__(self, inFileName: str, inLine: int, inFuncName: str) -> None: ...

	def empty(self) -> bool: ...

	@staticmethod
	def basename(inPath: str) -> str: ...

	filename: str
	short_filename: str
	line: int
	funcname: str

class log_msg:

	@overload
	def __init__(self) -> None: ...

	@overload
	def __init__(self, 
		inLogTime: datetime, inLocation: source_loc, 
		inLoggerName: str, inLevel: level, inMessage: str
	) -> None: ...

	@overload
	def __init__(self, 
		inLocation: source_loc, 
		inLoggerName: str, inLevel: level, inMessage: str
	) -> None: ...

	@overload
	def __init__(self, 
		inLoggerName: str, inLevel: level, inMessage: str
	) -> None: ...

	logger_name: str
	log_level: level
	time: datetime
	thread_id: int
	source: source_loc
	payload: str

	color_range_start: int
	color_range_end: int



class formatter:

	def __init__(self) -> None: ...

	def format(self, inMessage: log_msg) -> str: ...
	def clone(self) -> formatter: ...



class logger:

	@overload
	def __init__(self, inName: str) -> None: ...

	@overload
	def __init__(self, inName: str, inSink: sinks.sink) -> None: ...

	@overload
	def __init__(self, inName: str, inSink: Iterable[sinks.sink]) -> None: ...

	def set_level(self, inLevel: level) -> None: ...

	def trace(self, inMessage: str) -> None: ...
	def debug(self, inMessage: str) -> None: ...
	def info(self, inMessage: str) -> None: ...
	def warn(self, inMessage: str) -> None: ...
	def error(self, inMessage: str) -> None: ...
	def critical(self, inMessage: str) -> None: ...